
# ~BrieFlow analysis configuration file~

# All paths are resolved relative to the directory the workflow is run from.

# Parameters:
all:
  root_fp: brieflow_output/
preprocess:
  sbs_samples_fp: config/sbs_samples.tsv
  sbs_combo_fp: config/sbs_combo.tsv
  sbs_channel_order:
  - DAPI
  - GFP
  - Cy3
  - Far-red
  sbs_channel_order_flip: null
  sample_fraction: 1.0
